name: Node.js CI

on:
  [push, pull_request]
    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build iamge
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile.dev
          push: false
          tags: ${{secrets.DOCKERHUB_USERNAME}}/webapp:latest
      - 
        name: Run image
        uses: addnab/docker-run-action@v3
        with:
          image: ${{secrets.DOCKERHUB_USERNAME}}/webapp:latest
          run: docker run
